In [23]:
import sys
sys.path.append('../code/')

In [ ]:
import numpy as np
import pickle
import operator
import os
import time

from sklearn import svm, metrics

import wk
import ssk
import ngk

In [25]:
labels = {
    'acq': 0,
    'corn': 1,
    'crude': 2,
    'earn': 3
}

In [26]:
dataset = pickle.load(open('reuters470big.pkl', 'rb'))

In [54]:
num = 1

In [55]:
train_inputs = [tup[0] for tup in dataset['train'][::num]]
train_labels = np.array([labels[tup[1]] for tup in dataset['train'][::num]])

In [56]:
len(train_inputs)

380

In [57]:
test_inputs = [tup[0] for tup in dataset['test'][::num]]
test_labels = np.array([labels[tup[1]] for tup in dataset['test'][::num]])

In [58]:
len(test_inputs)

90

In [81]:
def compute_train_gram(docs, kernel=None):
    n = len(docs)
    gram = np.ones((n, n))
    for x in range(n):
        print('{0:.2f}%'.format(x / n))
        for y in range(x + 1, n):
            gram[x, y] = kernel(docs[x], docs[y])
            gram[y, x] = gram[x, y]
    return gram  

In [82]:
def compute_test_gram(test, train, kernel=None):
    gram = np.zeros((len(test), len(train)))
    for x in range(len(test)):
        print('{0:.2f}%'.format(x / len(test)))
        for y in range(len(train)):
            gram[x, y] = kernel(test[x], train[y])
    return gram  

In [83]:
kernel = lambda x, y: ssk.ssk(x, y, 2, 0.5)

In [84]:
train_gram = compute_train_gram(train_inputs, kernel=kernel)

0.00%
0.00%
0.01%
0.01%
0.01%
0.01%
0.02%
0.02%
0.02%
0.02%
0.03%
0.03%


KeyboardInterrupt: 

In [46]:
test_gram = compute_test_gram(test_inputs, train_inputs, kernel=kernel)

0 of 18
1 of 18
2 of 18
3 of 18
4 of 18
5 of 18
6 of 18
7 of 18
8 of 18
9 of 18
10 of 18
11 of 18
12 of 18
13 of 18
14 of 18
15 of 18
16 of 18
17 of 18


In [47]:
clf = svm.SVC(kernel='precomputed')

In [48]:
clf.fit(train_gram, train_labels)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto',
  kernel='precomputed', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [49]:
pred_labels = clf.predict(test_gram)
print(pred_labels)
print(test_labels)

[0 0 0 0 0 0 0 0 0 0 0 0 0 3 3 3 3 3]
[0 0 0 0 0 1 1 2 2 2 3 3 3 3 3 3 3 3]


In [50]:
precision, recall, fscore, _ = metrics.precision_recall_fscore_support(test_labels, pred_labels)
print(fscore)

[ 0.55555556  0.          0.          0.76923077]


/usr/local/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [52]:
train_inputs[56]

'electrosound group inc lt esg rd qtr feb loss oper shr loss one cts vs loss five cts oper net loss vs loss revs vs avg shrs vs nine mths oper shr profit cts vs profit cts oper net profit vs profit revs mln vs mln avg shrs vs note oper excludes tax losses vs qtr tax credits vs nine mths'

In [53]:
train_labels[56]

3